In [62]:
import pandas as pd

### Lendo os dados

In [63]:
data = pd.read_csv('../data/Prostata Quimioterapia SIA-SUS.csv', error_bad_lines=False, encoding='latin1')

In [64]:
data = data.drop('Unnamed: 0', 1)

#### Colunas

In [65]:
data.columns

Index(['AP_MVM', 'AP_CONDIC', 'AP_GESTAO', 'AP_CODUNI', 'AP_AUTORIZ', 'AP_CMP',
       'AP_PRIPAL', 'AP_VL_AP', 'AP_UFMUN', 'AP_TPUPS', 'AP_TIPPRE',
       'AP_MN_IND', 'AP_CNPJCPF', 'AP_CNPJMNT', 'AP_CNSPCN', 'AP_COIDADE',
       'AP_NUIDADE', 'AP_SEXO', 'AP_RACACOR', 'AP_MUNPCN', 'AP_UFNACIO',
       'AP_CEPPCN', 'AP_UFDIF', 'AP_MNDIF', 'AP_DTINIC', 'AP_DTFIM',
       'AP_TPATEN', 'AP_TPAPAC', 'AP_MOTSAI', 'AP_OBITO', 'AP_ENCERR',
       'AP_PERMAN', 'AP_ALTA', 'AP_TRANSF', 'AP_DTOCOR', 'AP_CODEMI',
       'AP_CATEND', 'AP_APACANT', 'AP_UNISOL', 'AP_DTSOLIC', 'AP_DTAUT',
       'AP_CIDCAS', 'AP_CIDPRI', 'AP_CIDSEC', 'AP_ETNIA', 'AQ_CID10',
       'AQ_LINFIN', 'AQ_ESTADI', 'AQ_GRAHIS', 'AQ_DTIDEN', 'AQ_TRANTE',
       'AQ_CIDINI1', 'AQ_DTINI1', 'AQ_CIDINI2', 'AQ_DTINI2', 'AQ_CIDINI3',
       'AQ_DTINI3', 'AQ_CONTTR', 'AQ_DTINTR', 'AQ_ESQU_P1', 'AQ_TOTMPL',
       'AQ_TOTMAU', 'AQ_ESQU_P2'],
      dtype='object')

In [66]:
data.describe()

,AP_MVM,AP_GESTAO,AP_CODUNI,AP_AUTORIZ,AP_CMP,AP_PRIPAL,AP_VL_AP,AP_UFMUN,AP_TPUPS,AP_TIPPRE,...,AP_TPAPAC,AP_ENCERR,AP_TRANSF,AP_DTSOLIC,AP_ETNIA,AQ_ESTADI,AQ_DTINI1,AQ_DTINI2,AQ_DTINI3,AQ_DTINTR
count,3.167299e+06,3.167299e+06,3.167299e+06,3.167299e+06,3.167299e+06,3.167299e+06,3.167299e+06,3.167299e+06,3.167299e+06,3.167299e+06,...,3.167299e+06,3.167297e+06,3.167298e+06,3.015190e+06,4.380000e+02,3.167298e+06,1.041343e+06,5.630790e+05,3.344750e+05,3.167297e+06
mean,2.016128e+05,3.359013e+05,2.150126e+06,3.364291e+12,2.016120e+05,3.040208e+08,3.364524e+02,3.366976e+05,6.864570e+00,1.857738e+01,...,1.651901e+00,5.674555e-03,1.000853e-04,2.016046e+07,4.610028e+04,2.823347e+00,1.843262e+07,1.614851e+07,1.289058e+07,2.014616e+07
std,1.420092e+02,8.035444e+04,1.054725e+06,8.031609e+11,1.417991e+02,4.276575e+03,2.519407e+02,8.034393e+04,8.513733e+00,2.635554e+01,...,4.763824e-01,7.511562e-02,1.019137e-02,1.399764e+05,9.637623e+05,1.139063e+00,5.559968e+06,8.006488e+06,9.663483e+06,1.914145e+05
min,2.014010e+05,1.100000e+05,3.960000e+02,1.114200e+12,2.014010e+05,3.040201e+08,0.000000e+00,1.100040e+05,5.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.932052e+07
25%,2.015040e+05,2.910800e+05,2.081644e+06,2.916201e+12,2.015040e+05,3.040201e+08,3.015000e+02,2.927400e+05,5.000000e+00,0.000000e+00,...,1.000000e+00,0.000000e+00,0.000000e+00,2.015040e+07,1.000000e+00,2.000000e+00,2.007030e+07,2.005060e+07,0.000000e+00,2.013102e+07
50%,2.016070e+05,3.304550e+05,2.255936e+06,3.317204e+12,2.016070e+05,3.040201e+08,3.015000e+02,3.304550e+05,5.000000e+00,0.000000e+00,...,2.000000e+00,0.000000e+00,0.000000e+00,2.016070e+07,5.900000e+01,3.000000e+00,2.011070e+07,2.011081e+07,2.011070e+07,2.015033e+07
75%,2.017110e+05,3.550300e+05,2.564211e+06,3.518241e+12,2.017100e+05,3.040201e+08,3.015000e+02,3.552200e+05,7.000000e+00,5.000000e+01,...,2.000000e+00,0.000000e+00,0.000000e+00,2.017100e+07,7.700000e+01,4.000000e+00,2.014051e+07,2.014063e+07,2.014100e+07,2.016093e+07
max,2.019030e+05,5.300000e+05,8.003629e+06,5.318202e+12,2.018120e+05,3.040503e+08,1.847150e+03,5.301800e+05,8.200000e+01,6.100000e+01,...,8.000000e+00,1.000000e+00,4.000000e+00,9.201081e+07,2.017010e+07,4.000000e+00,8.201061e+07,6.201090e+07,7.201043e+07,9.201063e+07

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3167299 entries, 0 to 3167298
Data columns (total 63 columns):
AP_MVM        int64
AP_CONDIC     object
AP_GESTAO     int64
AP_CODUNI     int64
AP_AUTORIZ    int64
AP_CMP        int64
AP_PRIPAL     int64
AP_VL_AP      float64
AP_UFMUN      int64
AP_TPUPS      int64
AP_TIPPRE     int64
AP_MN_IND     object
AP_CNPJCPF    int64
AP_CNPJMNT    float64
AP_CNSPCN     object
AP_COIDADE    int64
AP_NUIDADE    int64
AP_SEXO       object
AP_RACACOR    int64
AP_MUNPCN     int64
AP_UFNACIO    float64
AP_CEPPCN     object
AP_UFDIF      int64
AP_MNDIF      float64
AP_DTINIC     float64
AP_DTFIM      int64
AP_TPATEN     int64
AP_TPAPAC     int64
AP_MOTSAI     object
AP_OBITO      object
AP_ENCERR     float64
AP_PERMAN     object
AP_ALTA       object
AP_TRANSF     float64
AP_DTOCOR     object
AP_CODEMI     object
AP_CATEND     object
AP_APACANT    object
AP_UNISOL     object
AP_DTSOLIC    float64
AP_DTAUT      object
AP_CIDCAS     object
AP_CIDPRI     object
AP_CIDSEC     object
AP_ETNIA      float64
AQ_CID10      object
AQ_LINFIN     object
AQ_ESTADI     float64
AQ_GRAHIS     object
AQ_DTIDEN     object
AQ_TRANTE     object
AQ_CIDINI1    object
AQ_DTINI1     float64
AQ_CIDINI2    object
AQ_DTINI2     float64
AQ_CIDINI3    object
AQ_DTINI3     float64
AQ_CONTTR     object
AQ_DTINTR     float64
AQ_ESQU_P1    object
AQ_TOTMPL     object
AQ_TOTMAU     object
AQ_ESQU_P2    object
dtypes: float64(14), int64(18), object(31)
memory usage: 1.5+ GB

In [68]:
data.head()

,AP_MVM,AP_CONDIC,AP_GESTAO,AP_CODUNI,AP_AUTORIZ,AP_CMP,AP_PRIPAL,AP_VL_AP,AP_UFMUN,AP_TPUPS,...,AQ_CIDINI2,AQ_DTINI2,AQ_CIDINI3,AQ_DTINI3,AQ_CONTTR,AQ_DTINTR,AQ_ESQU_P1,AQ_TOTMPL,AQ_TOTMAU,AQ_ESQU_P2
0,201401,EP,120000,2001586,1213200186033,201401,304020079,301.5,120040,5,...,NaN,NaN,NaN,NaN,S,20121008.0,ZOLAD,24,15,EX
1,201401,EP,120000,2001586,1214200017569,201401,304020079,301.5,120040,5,...,NaN,NaN,NaN,NaN,S,20100920.0,ZOLAD,36,33,EX
2,201401,EP,120000,2001586,1214200017130,201401,304020079,751.0,120040,5,...,NaN,NaN,NaN,NaN,S,20121016.0,ZOLAD,24,15,EX+ZOMETA
3,201401,EP,120000,2001586,1213200179433,201401,304020079,301.5,120040,5,...,NaN,NaN,NaN,NaN,S,20130325.0,ZOLAD,24,9,EX
4,201401,EP,120000,2001586,1214200016975,201401,304020079,751.0,120040,5,...,NaN,NaN,NaN,NaN,S,20130619.0,ZOLAD,24,4,EX+ZOMETA

In [77]:
data[data['AP_CEPPCN'] == 4533013]

,AP_MVM,AP_CONDIC,AP_GESTAO,AP_CODUNI,AP_AUTORIZ,AP_CMP,AP_PRIPAL,AP_VL_AP,AP_UFMUN,AP_TPUPS,...,AQ_CIDINI2,AQ_DTINI2,AQ_CIDINI3,AQ_DTINI3,AQ_CONTTR,AQ_DTINTR,AQ_ESQU_P1,AQ_TOTMPL,AQ_TOTMAU,AQ_ESQU_P2
2429913,201406,EP,350000,6123740,3514219767531,201405,304020079,301.50,355030,7,...,NaN,NaN,NaN,NaN,N,20140523.0,ZOL,60,0,NaN
2440109,201406,EP,350000,6123740,3514219767531,201406,304020079,301.50,355030,7,...,NaN,NaN,NaN,NaN,N,20140523.0,ZOL,60,0,NaN
2443879,201407,EP,350000,6123740,3514219767531,201407,304020079,0.00,355030,7,...,NaN,NaN,NaN,NaN,N,20140523.0,ZOL,60,0,NaN
2479565,201410,EP,350000,6123740,3514242036932,201410,304020079,301.50,355030,7,...,NaN,NaN,NaN,NaN,N,20140523.0,ZOL,60,3,NaN
2502867,201411,EP,350000,6123740,3514242036932,201411,304020079,301.50,355030,7,...,NaN,NaN,NaN,NaN,N,20140523.0,ZOL,60,3,NaN
2509624,201412,EP,350000,6123740,3514242036932,201412,304020079,301.50,355030,7,...,NaN,NaN,NaN,NaN,N,20140523.0,ZOL,60,3,NaN
2528674,201501,EP,350000,6123740,3515202021914,201501,304020079,301.50,355030,7,...,NaN,NaN,NaN,NaN,N,20140523.0,ZOL,60,6,NaN
2534811,201502,EP,350000,6123740,3515202021914,201502,304020079,301.50,355030,7,...,NaN,NaN,NaN,NaN,N,20140523.0,ZOL,60,6,NaN
2544643,201503,EP,350000,6123740,3515202021914,201503,304020079,301.50,355030,7,...,NaN,NaN,NaN,NaN,N,20140523.0,ZOL,60,6,NaN
2569757,201505,EP,350000,6123740,3515218291233,201504,304020087,1062.65,355030,7,...,NaN,NaN,NaN,NaN,S,20150401.0,DOCET,12,0,AXEL
2580795,201505,EP,350000,6123740,3515218291233,201505,304020087,1062.65,355030,7,...,NaN,NaN,NaN,NaN,S,20150401.0,DOCET,12,0,AXEL
2587721,201506,EP,350000,6123740,3515218291233,201506,304020087,1062.65,355030,7,...,NaN,NaN,NaN,NaN,S,20150401.0,DOCET,12,0,AXEL
2602753,201507,EP,350000,6123740,3515235229649,201507,304020087,1062.65,355030,7,...,NaN,NaN,NaN,NaN,S,20150401.0,DOCET,12,3,AXEL
2613548,201508,EP,350000,6123740,3515235229649,201508,304020087,1062.65,355030,7,...,NaN,NaN,NaN,NaN,S,20150401.0,DOCET,12,3,AXEL
2623489,201509,EP,350000,6123740,3515235229649,201509,304020087,1062.65,355030,7,...,NaN,NaN,NaN,NaN,S,20150401.0,DOCET,12,3,AXEL
2636017,201510,EP,350000,6123740,3515247177409,201510,304020087,1062.65,355030,7,...,NaN,NaN,NaN,NaN,S,20150401.0,DOCET,12,6,AXEL
2648142,201511,EP,350000,6123740,3515247177409,201511,304020087,1062.65,355030,7,...,NaN,NaN,NaN,NaN,S,20150401.0,DOCET,012,6,AXEL
2670182,201512,EP,350000,6123740,3515247177409,201512,304020087,1062.65,355030,7,...,NaN,NaN,NaN,NaN,S,20150401.0,DOCET,12,6,AXEL

In [72]:
type(data['AP_CEPPCN'].iloc[0])

int